### ISSUE TITLE
Team Onboarding

### ISSUE THREAD

**Issue by mpeng8** [mpeng8/PyTrade#14]
## Story Details
- [x] Setup project github repository
- [x] Setup Zenhub for the project
- [x] Configure development environment 

## Acceptance Scenarios
Given: A team member 
When: the team member tries to use Github for the project
Then: the team member should be able to contribute as he/she wants.

Given: A team member 
When: the team member tries to use Zenhub for the project
Then: the team member should be able to contribute as he/she wants.

Given: A team member 
When: the team member tries to use the code for the project
Then: the team member should be able to run the current prototype.

## Done Done Criteria
Each team member has the access to Zenhub and Github.
